# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_key',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
